"$schema" = "https://starship.rs/config-schema.json"

palette = "catppuccin_mocha"

format = """
[](lavender)\
$os\
$username\
[](bg:blue fg:lavender)\
$directory\
[](fg:blue bg:green)\
$git_branch\
$git_status\
[](fg:green bg:teal)\
$c\
$rust\
$golang\
$nodejs\
$python\
$java\
$kotlin\
$lua\
[](fg:teal bg:surface0)\
$docker_context\
[](fg:surface0 bg:mauve)\
$time\
[ ](fg:mauve)\
$line_break\
$character"""

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:lavender fg:base"

[os.symbols]
Fedora = " "
Linux = " "

[username]
show_always = false
style_user = "bg:lavender fg:base"
style_root = "bg:lavender fg:red"
format = "[$user ]($style)"

[directory]
style = "bg:blue fg:base"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = " "
"Music" = "Û∞ùö "
"Pictures" = " "
"Developer" = "Û∞≤ã "
"Projects" = "Û∞≤ã "

[git_branch]
symbol = ""
style = "bg:green fg:base"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:green fg:base"
format = "[$all_status$ahead_behind ]($style)"

[nodejs]
symbol = ""
style = "bg:teal fg:base"
format = "[ $symbol ($version) ]($style)"

[c]
symbol = " "
style = "bg:teal fg:base"
format = "[ $symbol ($version) ]($style)"

[rust]
symbol = "ü¶Ä"
style = "bg:teal fg:base"
format = "[ $symbol ($version) ]($style)"

[golang]
symbol = ""
style = "bg:teal fg:base"
format = "[ $symbol ($version) ]($style)"

[python]
symbol = ""
style = "bg:teal fg:base"
format = "[ $symbol ($version) ]($style)"

[java]
symbol = ""
style = "bg:teal fg:base"
format = "[ $symbol ($version) ]($style)"

[kotlin]
symbol = ""
style = "bg:teal fg:base"
format = "[ $symbol ($version) ]($style)"

[lua]
symbol = ""
style = "bg:teal fg:base"
format = "[ $symbol ($version) ]($style)"

[docker_context]
symbol = ""
style = "bg:surface0 fg:text"
format = "[ $symbol $context ]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:mauve fg:base"
format = "[ Û∞•î $time ]($style)"

[character]
success_symbol = "[‚ùØ](bold green)"
error_symbol = "[‚ùØ](bold red)"

[cmd_duration]
min_time = 2_000
format = "took [$duration](bold yellow) "
